### ISSUE TITLE
Apoiadores

### ISSUE THREAD

**Issue by mairacanal** [zenitheesc/zenith-website#10]
Apesar de já possuir responsividade e funcionar em dispositivos Android, ainda falta acertar o grid em dispositivos iOS. 

### Detalhes
Em dispositivos iOS, os grid ficam muito grandes e em formato retangular ao invés do formato quadrado.

### Sugestões
O grid poderia ser responsivo, tal que, na medida em que apoiadores são adicionados no json, o grid é atualizado.

**Comment by jorgemrisco** [comment]
O bap sugeriu colocar só 4 caixinhas, formando um grid 2x2 pra evitar as duas caixas vazias no fim

![image](https://user-images.githubusercontent.com/61189874/111883257-eb42f400-8998-11eb-8276-8d81db6c49c0.png)

**Comment by mairacanal** [comment]
Vou fazer isso, sim. Quando a gnt tiver mais apoiadores, ai a gnt coloca as 6.
