### ISSUE TITLE
Inserir os CubeSats renderizados na página de Projetos

### ISSUE THREAD

**Issue by mairacanal** [zenitheesc/zenith-website#15]
Os CubeSats devem ser colocados no hero principal da página de projetos e posicionados em seus respectivos projetos na seção de CubeSats. 

## Detalhes
Um dos CubeSats ainda não foi renderizado pelo @jorgemrisco, porque ele não conseguiu abrir o arquivo.

**Comment by jorgemrisco** [comment]
Subirei as fotos estáticas que o bap enviou do UspSat (o que não temos o arquivo 3d) no drive até hoje a noite.

**Comment by jorgemrisco** [comment]
Pasta com as fotos:
https://drive.google.com/drive/u/1/folders/1xH9UCMb9gAZdByE3HhWuZEqImxif2tTQ
