### ISSUE TITLE
Error: Margem no final da página

### ISSUE THREAD

**Issue by Math-42** [zenitheesc/zenith-website#6]
### Describe the Error

Uma margem fantasma aparece depois do footer caso tente trocar de página sem estar no topo do site.

![WhatsApp Image 2021-03-05 at 4 13 26 PM](https://user-images.githubusercontent.com/43853194/110165210-5e613d80-7dd1-11eb-8a54-8483f14700ca.jpeg)

**Comment by jorgemrisco** [comment]
Emq branch q é? chequei em umas n encontrei

**Comment by jorgemrisco** [comment]
Adicionando informação para o pessoal do futuro:

Aparentemente tal comportamento apenas ocorre no navegador [Vivaldi](https://vivaldi.com/); Apesar de ele ser baseado em _chromium_ tal bug não persistiu em outros navegadores da mesma família.
